# Generated by Django 4.2 on 2024-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(choices=[(0, '  Nữ'), (1, 'Nam'), (2, 'Không xác định')], default=2),
        ),
    ]
